apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-model-serving-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ml-model-serving
      tier: serving
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
